### ISSUE TITLE
horizon.py failing on master (kilo)

### ISSUE THREAD

**Issue by mattt416** [rcbops/rpc-maas#201]
horizon.py is currently failing when using requests 2.6.2 with the following error:

```
status error While logging in: ('Connection aborted.', ResponseNotReady())
```

The stack trace being caught is:

```
Traceback (most recent call last):
  File "./horizon_check.py", line 105, in <module>
    main(args)
  File "./horizon_check.py", line 96, in main
    check(args)
  File "./horizon_check.py", line 77, in check
    verify=False)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 508, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ResponseNotReady())
```

If I downgrade requests to <2.6.1 this plugin seems to work fine.

**Comment by sigmavirus24** [comment]
The title is misleading but you're encountering https://github.com/kennethreitz/requests/issues/2568

This is a bug in urllib3 which we believe has been fixed in the following pull requests:

- https://github.com/shazow/urllib3/pull/599
- https://github.com/shazow/urllib3/pull/605

Requests 2.7.0 should be out soon fixing this issue.

**Comment by mattt416** [comment]
We're now installing requests 2.7.0, which is no longer affected by this.  Closing.

**Comment by claco** [comment]
@mattt416 @sigmavirus24 Does this effect Juno at all?

**Comment by mattt416** [comment]
@claco shouldn't: https://github.com/stackforge/os-ansible-deployment/blob/juno/requirements.txt#L8

**Comment by BjoernT** [comment]
@mattt416 @sigmavirus24 @claco Yes it does affect juno. You guys were looking at the wrong requirements.txt, the rpc-maas in juno is hosed and does not limit the version https://github.com/rcbops/rpc-maas/blob/juno/requirements.txt#L2

**Comment by mattt416** [comment]
@BjoernT We do use that requirements.txt file but it will be used _after_ pip.conf is configured w/ the RPC mirror, and that should have built the version of requests specified in os-a-d's requirements.txt.  Are you actively seeing broken juno deploys here?

/cc @sigmavirus24 @claco

**Comment by BjoernT** [comment]
Yes I had one deployment having 2.6.0 installed and I did manually downgrade to 2.4.1. They used MAAS 10.1.3 version

**Comment by sigmavirus24** [comment]
@BjoernT was the pip.conf not in place? The only way to get 2.6.0 would have been from PyPI because http://mirror.rackspace.com/rackspaceprivatecloud/python_packages/10.1.3/ has 2.4.1

**Comment by BjoernT** [comment]
The pip.conf was in place but I did not look into it because I did upgrade to 10.1.4 and that repository had 2.6.0 in, along with 2.4.1. Now it appears that we have remove 2.6.0 so it would not happen again

**Comment by BjoernT** [comment]
@mattt416 @sigmavirus24 @claco 
This check is still failing on a new 10.1.5 build:

status error module>\n    main(args)\n  File "./horizon_check.py", line 100, in main\n    check(args)\n  File "./horizon_check.py", line 29, in check\n    requests.packages.urllib3.disable_warnings()\nAttributeError: 'module' object has no attribute 'disable_warnings'\n
Traceback (most recent call last):
  File "./horizon_check.py", line 109, in <module>
    main(args)
  File "./horizon_check.py", line 100, in main
    check(args)
  File "./horizon_check.py", line 29, in check
    requests.packages.urllib3.disable_warnings()
AttributeError: 'module' object has no attribute 'disable_warnings'

Installed libs: 
requests==2.2.1
urllib3==1.10.4

**Comment by mattt416** [comment]
Hi @BjoernT,

I've confirmed this is a problem.  @cloudnull or @sigmavirus24, do either of you know why we're now building requests 2.2.1 in juno/10.1.5?  I can see that we no longer pin to requests 2.4.1 however I don't see why we'd end up building such an old version of requests.

--Matt

**Comment by BjoernT** [comment]
@cloudnull  @sigmavirus24 @mattt416 Can we get this resolved ? I don't want to hand over environments with failed horizon checks....

**Comment by sigmavirus24** [comment]
Sorry, I missed this while I was at the summit. I have no clue why 2.2.1 is being built for 10.1.5, that said, a conditional check before calling `disable_warnings` would work (like the one I had sent in a PR earlier) because 2.2.1 does not in fact issue warnings so there's nothing to disable.

**Comment by BjoernT** [comment]
This issue is present since 10.1.4 (maybe even 10.1.3). I'm not eager to remove the disable_warnings from the maas checks since we still have the problem that the maas checks do not update properly during upgrade (See https://github.com/rcbops/rpc-extras/issues/95)  So we would most likely run outdated and/or modified checks after upgrades. Since we had requests 2.4.1 before I don't know why we downgraded to that version just recently

**Comment by sigmavirus24** [comment]
@BjoernT "conditional check before calling `disable_warnings`" means we would only call `disable_warnings` if it is present to be called. This means that if some ancient version of requests is installed by some evil magic, then we don't stacktrace. If a new version is installed, then in fact it will be called.

**Comment by mattt416** [comment]
I was digging around to see why we have a lower version of requests in 10.1.5 onwards and the version we now build does align with https://github.com/openstack/requirements/blob/stable/juno/global-requirements.txt:

requests>=2.1.0,!=2.4.0,<=2.2.1

This then raises the question as to how we were getting a newer version in previous tags, but at least we are now building requests correctly.

**Comment by sigmavirus24** [comment]
> This then raises the question as to how we were getting a newer version in previous tags, but at least we are now building requests correctly.

One of the OpenStack client releases broke the gate along the way and some people went through and applied upper caps on all the dependencies based off of (what I still insist) was a fault list of dependency versions being tested at the gate.

**Comment by BjoernT** [comment]
@sigmavirus24 @mattt416 
This issue is still present on new builds with 10.1.8, can we get this reopened

 #python /usr/lib/rackspace-monitoring-agent/plugins/horizon_check.py 172.29.237.146
status error orizon_check.py", line 100, in main\n    check(args)\n  File "/usr/lib/rackspace-monitoring-agent/plugins/horizon_check.py", line 29, in check\n    requests.packages.urllib3.disable_warnings()\nAttributeError: 'module' object has no attribute 'packages'\n
Traceback (most recent call last):
  File "/usr/lib/rackspace-monitoring-agent/plugins/horizon_check.py", line 109, in <module>
    main(args)
  File "/usr/lib/rackspace-monitoring-agent/plugins/horizon_check.py", line 100, in main
    check(args)
  File "/usr/lib/rackspace-monitoring-agent/plugins/horizon_check.py", line 29, in check
    requests.packages.urllib3.disable_warnings()
AttributeError: 'module' object has no attribute 'packages'

# pip list | egrep 'requests|urllib3'
requests (2.2.1)
urllib3 (1.7.1)

**Comment by BjoernT** [comment]
@sigmavirus24 @mattt416  BUMP

**Comment by claco** [comment]
Bumps aren't how this is supported to work. :-) Please bring this to the rpc bug triage meeting tomorrow.

**Comment by BjoernT** [comment]
I try every channel possible. We still have the problem and I can't understand that this bug is closed

**Comment by mattt416** [comment]
Hi @BjoernT, we've had https://github.com/rcbops/rpc-maas/pulls open for quite some time.  I've already :+1: it but I'll make sure someone else reviews this morning so it gets merged.

@nrb @claco can you guys please make sure the above commit is included when we cut the next 10.x tag?

**Comment by BjoernT** [comment]
Yeah @mattt416  the https://github.com/rcbops/rpc-maas/pull/211 never made it into the Juno branch, until 5 hours ago, so we missed it for 10.1.9.

**Comment by nrb** [comment]
@mattt416 @BjoernT This will get into 10.1.10.
